import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen justify-between`}
      >
        <div>
          <header className="bg-slate-200 p-4 rounded-full m-2 sticky top-2">
            <h1 className="text-xl font-bold">Yo Linkeado</h1>
          </header>
          <main>
            {children}
          </main>
        </div>
        <footer className="">Footer</footer>
      </body>
    </html>
  );
}
